FROM node:22-alpine AS build

WORKDIR /frontend

COPY . .
COPY .env.frontend.prod ../.env

RUN npm ci

RUN npm run build

FROM nginx:stable-alpine

COPY --from=build /frontend/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
